### ISSUE TITLE
Observability in CI

### ISSUE THREAD

**Issue by mcataford** [christrotter/gootsmoji#10]
Recent CI failures revealed that there's not a whole lot of visibility into failures when they happen in CI. Can we instrument this?

**Comment by mcataford** [comment]
I think OTel has something that could help us.

**Comment by christrotter** [comment]
i found the CI issue - was not visibility, was misunderstanding what was even going on.   whiiiich you could argue is visibility.

anyways i made the CI fire less often and simplified it a bit.
