### ISSUE TITLE
[Updates] Merge Updated Goots From Slack

### ISSUE THREAD

**Issue by keller-tophat** [christrotter/gootsmoji#21]
The updates to neck v2.0 and rewrite from stickman.js to th-gootsarms haven't been merged.

Goots needing a merge:
- :cant-hear-goots:
- :goots-angry:
- :eugene-goots:
- :goots-intrigued:
- :gootprised:

**Comment by christrotter** [comment]
I checked - I think the confusion is that some of the old ones I left in.  All the new ones are there I'm pretty sure.
