### ISSUE TITLE
Panic is a valid state of being, Goots Panik would be useful to express that

### ISSUE THREAD

**Issue by mcataford** [christrotter/gootsmoji#40]
Even through the late Kobe Bryant said

> If I panic, everyone else panics.

this is not a thought he could express via the medium of goots. I imagine that a Goots Panik emoji might take inspiration from the image below and provide peace for those with panic on their minds.

![image](https://github.com/christrotter/gootsmoji/assets/6210361/29b345af-ee4f-4b0e-a15c-e1a4b5b79f20)

**Comment by christrotter** [comment]
closed with https://github.com/christrotter/gootsmoji/pull/59
