### ISSUE TITLE
grid builder works locally, not in gha?

### ISSUE THREAD

**Issue by christrotter** [christrotter/gootsmoji#56]
Very confusing.  I ran locally and it works fine.
in gha it seems to add.  but, no new goots.

**Comment by keller-tophat** [comment]
Commit looks fine:
https://github.com/christrotter/gootsmoji/commit/952d59036ce120d24316ba0ecabbc901019bc532
Could it be an HTTP caching issue?

**Comment by christrotter** [comment]
seems working now.  i tried a few options.  but is fix.  you fix.
