### ISSUE TITLE
missing goots

### ISSUE THREAD

**Issue by christrotter** [christrotter/gootsmoji#61]
- wat goots
- thanks goots / big thumbsup
- PR goots
- science goots
- goots ok
- gootcha
- goots-i-have-the-power
- goots-huh

**Comment by scott-hannan** [comment]
dibs science goots

**Comment by scott-hannan** [comment]
:goots-oh-you:

**Comment by scott-hannan** [comment]
:rootin-tooting-shootin-goot-off: ive got an idea here

**Comment by christrotter** [comment]
:goots-roll-out:

**Comment by christrotter** [comment]
goots ship it.

**Comment by scott-hannan** [comment]
:goots siren: or :goots alarm:

**Comment by scott-hannan** [comment]
:goots-announcement: with like a megaphone or somethin

**Comment by christrotter** [comment]
will do these on the weekend

**Comment by christrotter** [comment]
I have done all that i can.
https://github.com/christrotter/gootsmoji/pull/65
