### ISSUE TITLE
TopHat Monocle GOoOoOOoOoooOOoOOOots

### ISSUE THREAD

**Issue by mw-root** [christrotter/gootsmoji#67]
## Description

Hello Christopher, we sure would like a fancy goots wearing a tophat and/or a monocle.

![image](https://github.com/christrotter/gootsmoji/assets/12434761/0ee8e5c9-0c26-48f8-9428-993b317e23a0)

**Comment by christrotter** [comment]
https://github.com/christrotter/gootsmoji/pull/68
