### ISSUE TITLE
More goots

### ISSUE THREAD

**Issue by scott-hannan** [christrotter/gootsmoji#69]
Crying cool cowboy goots
skullet-goots

**Comment by christrotter** [comment]
pirate goots

**Comment by scott-hannan** [comment]
party popper goots

**Comment by christrotter** [comment]
offboard goots

**Comment by scott-hannan** [comment]
there aint room in the town for the goot of us

**Comment by christrotter** [comment]
"goorage" (courage)

**Comment by scott-hannan** [comment]
vacation goots, chillin goots

**Comment by christrotter** [comment]
doctor goots, gootspeed

**Comment by christrotter** [comment]
c/o bossman: `LGootsTM!`

**Comment by christrotter** [comment]
doctor goots

**Comment by christrotter** [comment]
sick goots, feel-better goots

**Comment by christrotter** [comment]
Closed in https://github.com/christrotter/gootsmoji/pull/72
