### ISSUE TITLE
Upgrade to Python 3.12

### ISSUE THREAD

**Issue by mcataford** [christrotter/gootsmoji#8]
The application is not prescriptive about Python versions, but CI mentions 3.10 - [3.10 reached EOL more than a year ago](https://endoflife.date/python). This poses security risks for high-stakes gootsing processes.

**Comment by christrotter** [comment]
actually working on this.  learning opportunity - when starting this issue i had no clue how you would take a 'from nothing' repo and ensure there is a standard python version.  discovered this is done via repo bootstrap type scripts, and pyenv.  so adding pyenv.

**Comment by christrotter** [comment]
Fixed with https://github.com/christrotter/gootsmoji/pull/25
